version: "3.8"

services:
    apache-fpm:
        build:
            context: ./.docker/apache/fpm
        container_name: laravel-apache-fpm
        working_dir: /app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel-apache-fpm.rule=Host(`laravel-apache-fpm`)"
        networks:
            - traefik-network
        volumes:
            - ./:/app
        expose:
            - 80

    laravel-php-fpm:
        build:
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        container_name: laravel-php-fpm
        working_dir: /app
        tty: true
        networks:
            - traefik-network
        volumes:
            - ./:/app
            - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

networks:
    traefik-network:
        external: true
