version: "3.8"

services:
    node:
        container_name: reveal-node-traefik
        tty: true
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "8888:8000"
        volumes:
            - ./:/app