version: "3.7"

services:
  web:
    image: nginx:1.19-alpine
    container_name: blumilk-meetup-sql-injection-web
    working_dir: /application
    tty: true
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2667:80"

  php:
    image: ghcr.io/blumilksoftware/php:8.0.7.0
    container_name: blumilk-meetup-sql-injection-php
    working_dir: /application
    user: "1000"
    volumes:
      - .:/application
